// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYEMHqns6cWhAc3dPmwBJOB2Hs_4j-mw0',
    appId: '1:647166159436:web:063f58144f19c459bca2e9',
    messagingSenderId: '647166159436',
    projectId: 'fluttermovieapp-a79ba',
    authDomain: 'fluttermovieapp-a79ba.firebaseapp.com',
    storageBucket: 'fluttermovieapp-a79ba.firebasestorage.app',
    measurementId: 'G-QS45L347TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_e9NOermjYVXkpnVr892DmFEdnoCVP2M',
    appId: '1:647166159436:android:4e2023bfcd8f9459bca2e9',
    messagingSenderId: '647166159436',
    projectId: 'fluttermovieapp-a79ba',
    storageBucket: 'fluttermovieapp-a79ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFXYWch73M6oRnNaLrEGgqh8Ncrd82UI8',
    appId: '1:647166159436:ios:afc25ccf9505ac14bca2e9',
    messagingSenderId: '647166159436',
    projectId: 'fluttermovieapp-a79ba',
    storageBucket: 'fluttermovieapp-a79ba.firebasestorage.app',
    androidClientId: '647166159436-h67ntc19i8klilka9343cfikl4gn57gn.apps.googleusercontent.com',
    iosClientId: '647166159436-q1tka8nmgbqkrdfvqiirl82jvsasso73.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMovieApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFXYWch73M6oRnNaLrEGgqh8Ncrd82UI8',
    appId: '1:647166159436:ios:afc25ccf9505ac14bca2e9',
    messagingSenderId: '647166159436',
    projectId: 'fluttermovieapp-a79ba',
    storageBucket: 'fluttermovieapp-a79ba.firebasestorage.app',
    androidClientId: '647166159436-h67ntc19i8klilka9343cfikl4gn57gn.apps.googleusercontent.com',
    iosClientId: '647166159436-q1tka8nmgbqkrdfvqiirl82jvsasso73.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMovieApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYEMHqns6cWhAc3dPmwBJOB2Hs_4j-mw0',
    appId: '1:647166159436:web:01ee983a56588206bca2e9',
    messagingSenderId: '647166159436',
    projectId: 'fluttermovieapp-a79ba',
    authDomain: 'fluttermovieapp-a79ba.firebaseapp.com',
    storageBucket: 'fluttermovieapp-a79ba.firebasestorage.app',
    measurementId: 'G-RC37TE8LJJ',
  );
}
